// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by hive_generator. Run: flutter pub run build_runner build
part of 'transaction_model.dart';

class TransactionModelAdapter extends TypeAdapter<TransactionModel> {
  @override
  final int typeId = 0;

  @override
  TransactionModel read(BinaryReader reader) {
    final fields = reader.readMap();
    return TransactionModel(
      id: fields[0] as String,
      dateTime: fields[1] as DateTime,
      type: fields[2] as String,
      category: fields[3] as String,
      amountUSD: fields[4] as double,
      description: fields[5] as String,
    );
  }

  @override
  void write(BinaryWriter writer, TransactionModel obj) {
    writer.writeMap({
      0: obj.id,
      1: obj.dateTime,
      2: obj.type,
      3: obj.category,
      4: obj.amountUSD,
      5: obj.description,
    });
  }
}
